import { useEffect, useMemo, useState } from 'react';
import { api, type AgentSession, type EventRecord, type ExecutionAttempt, type Objective, type Project } from '../api/client';
import { summarizeEventPayload } from '../lib/event-summary';
import { OBJECTIVE_STATUS_LABEL, SESSION_STATUS_LABEL } from '../lib/labels';

interface Props { projects: Project[]; objectivesByProject: Record<string, Objective[]>; sessionsByObjective: Record<string, AgentSession[]>; }
type Worker = { id: string; task: string | null; events: EventRecord[] };

const live = (value: Objective) => ['IN_AVVIO', 'IN_LAVORAZIONE'].includes(value.status);
const money = (value: number) => value > 0 ? `€ ${value.toFixed(4)}` : '—';
function duration(ms: number | null, from?: string | null) { const value = ms ?? (from ? Math.max(0, Date.now() - new Date(from).getTime()) : null); if (value === null) return '—'; const s = Math.floor(value / 1000); return s < 60 ? `${s}s` : `${Math.floor(s / 60)}m ${s % 60}s`; }
function kind(event: EventRecord) { const text = `${event.type} ${JSON.stringify(event.payload ?? '')}`.toLowerCase(); return text.includes('heartbeat') ? 'heartbeat' : text.includes('fallback') ? 'fallback' : text.includes('retry') ? 'retry' : text.includes('tool') ? 'tool' : 'event'; }
function worker(event: EventRecord): { id: string; task: string | null } | null { if (!event.payload || typeof event.payload !== 'object' || Array.isArray(event.payload)) return null; const p = event.payload as Record<string, unknown>; const m = p.metadata && typeof p.metadata === 'object' ? p.metadata as Record<string, unknown> : {}; const id = [p.workerId, p.worker_id, p.agentId, p.agent_id, m.workerId, m.agentId].find((v): v is string => typeof v === 'string' && !!v.trim()); if (!id) return null; const task = [p.taskId, p.task_id, m.taskId].find((v): v is string => typeof v === 'string' && !!v.trim()) ?? null; return { id, task }; }
const raw = (value: unknown) => JSON.stringify(value, null, 2);

export function ActivityMonitorView({ projects, objectivesByProject, sessionsByObjective }: Props) {
  const objectives = useMemo(() => Object.values(objectivesByProject).flat().sort((a, b) => Number(live(b)) - Number(live(a)) || new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()), [objectivesByProject]);
  const [selectedId, setSelectedId] = useState(''); const [events, setEvents] = useState<EventRecord[]>([]); const [attempts, setAttempts] = useState<ExecutionAttempt[]>([]); const [loading, setLoading] = useState(false);
  useEffect(() => { if (!selectedId && objectives[0]) setSelectedId(objectives[0].id); }, [selectedId, objectives]);
  useEffect(() => { if (selectedId && !objectives.some((o) => o.id === selectedId)) setSelectedId(objectives[0]?.id ?? ''); }, [selectedId, objectives]);
  const objective = objectives.find((o) => o.id === selectedId) ?? null; const sessions = objective ? sessionsByObjective[objective.id] ?? [] : []; const project = objective ? projects.find((p) => p.id === objective.projectId) : null;
  useEffect(() => { if (!objective) { setEvents([]); setAttempts([]); return; } let alive = true; const load = async () => { setLoading(true); try { const [eventResponse, responses] = await Promise.all([api.listEvents({ objectiveId: objective.id, limit: 200 }), Promise.all(sessions.map((s) => api.listExecutionAttempts(s.id)))]); if (alive) { setEvents(eventResponse.events); setAttempts(responses.flatMap((r) => r.attempts)); } } finally { if (alive) setLoading(false); } }; void load(); const timer = window.setInterval(() => void load(), 5_000); return () => { alive = false; window.clearInterval(timer); }; }, [objective?.id, sessions.map((s) => s.id).join(',')]);
  const orderedAttempts = useMemo(() => [...attempts].sort((a, b) => a.attemptIndex - b.attemptIndex), [attempts]); const current = orderedAttempts.find((a) => !a.endedAt) ?? orderedAttempts[orderedAttempts.length - 1] ?? null; const activeSession = sessions.find((s) => s.status === 'ATTIVA' || s.status === 'IN_AVVIO') ?? sessions[sessions.length - 1] ?? null; const total = orderedAttempts.reduce((sum, a) => sum + (a.costActual ?? a.costEstimate ?? 0), 0);
  const workers = useMemo(() => { const all = new Map<string, Worker>(); for (const event of events) { const found = worker(event); if (!found) continue; const item = all.get(found.id) ?? { id: found.id, task: found.task, events: [] }; item.events.push(event); all.set(found.id, item); } return [...all.values()]; }, [events]);
  return <div className="activity-monitor"><section className="panel activity-monitor-head"><div><p className="eyebrow">Monitor attività</p><h1>Segui un obiettivo</h1><p className="muted">Aggiornamento automatico ogni 5 secondi · solo dati già persistiti.</p></div><label className="select-label">Obiettivo<select value={selectedId} onChange={(e) => setSelectedId(e.target.value)}>{objectives.map((o) => <option key={o.id} value={o.id}>{OBJECTIVE_STATUS_LABEL[o.status]} · {o.title}</option>)}</select></label></section>
    {!objective ? <section className="panel"><p className="muted">Nessun obiettivo attivo o recente da monitorare.</p></section> : <><section className="monitor-summary"><div className="kpi"><span className="kpi-label">Stato</span><strong className="kpi-value">{OBJECTIVE_STATUS_LABEL[objective.status]}</strong><span className="muted small">{project?.name ?? '—'}</span></div><div className="kpi"><span className="kpi-label">Runtime</span><strong className="kpi-value">{current?.runtimeName ?? activeSession?.agentType ?? '—'}</strong><span className="muted small">{current?.providerName ?? activeSession?.executionSelection?.providerId ?? '—'} / {current?.modelName ?? activeSession?.executionSelection?.modelId ?? 'modello runtime'}</span></div><div className="kpi"><span className="kpi-label">Costo</span><strong className="kpi-value">{money(total)}</strong><span className="muted small">{orderedAttempts.length} tentativi</span></div><div className="kpi"><span className="kpi-label">Durata</span><strong className="kpi-value">{duration(current?.durationMs ?? null, current?.startedAt ?? objective.startedAt)}</strong><span className="muted small">{activeSession?.lastHeartbeatAt ? `Heartbeat ${new Date(activeSession.lastHeartbeatAt).toLocaleTimeString('it-IT')}` : 'Nessun heartbeat'}</span></div></section>
      <div className="monitor-grid"><section className="panel monitor-main"><div className="panel-head"><h2>Attività</h2><span className="muted small">{loading ? 'Aggiornamento…' : `${events.length} eventi`}</span></div>{events.length === 0 ? <p className="muted">Nessun evento registrato.</p> : <ol className="monitor-timeline">{events.map((event) => { const type = kind(event); return <li key={event.id} className={`monitor-event monitor-event-${type}`}><time>{new Date(event.timestamp).toLocaleTimeString('it-IT')}</time><span className="monitor-event-kind">{type}</span><div><strong>{event.type}</strong><p>{summarizeEventPayload(event.payload) || event.type.replace(/\./g, ' ')}</p>{event.payload !== null && <details><summary>Dettagli tecnici raw</summary><pre>{raw(event.payload)}</pre></details>}</div></li>; })}</ol>}</section>
        <aside className="monitor-side"><section className="panel"><div className="panel-head"><h2>Tentativi e recovery</h2></div><ol className="attempt-list">{orderedAttempts.map((attempt) => <li key={attempt.id}><strong>#{attempt.attemptIndex} · {attempt.status}</strong><span>{attempt.runtimeName ?? 'runtime'} / {attempt.providerName ?? 'provider'} / {attempt.modelName ?? 'modello runtime'}</span><span>{duration(attempt.durationMs, attempt.startedAt)} · {money(attempt.costActual ?? attempt.costEstimate ?? 0)}</span>{(attempt.attemptIndex > 1 || attempt.fallbackOfAttemptId) && <em>{attempt.fallbackOfAttemptId ? 'Fallback' : 'Retry'}</em>}{attempt.reason && <p className="muted small">{attempt.reason}</p>}<details><summary>Dettagli tecnici raw</summary><pre>{raw(attempt.metadata)}</pre></details></li>)}</ol>{orderedAttempts.length === 0 && <p className="muted">Nessun tentativo registrato.</p>}</section><section className="panel"><div className="panel-head"><h2>Sessioni</h2></div><ul className="monitor-sessions">{sessions.map((s) => <li key={s.id}><strong>{SESSION_STATUS_LABEL[s.status]}</strong><span>{s.agentType} · heartbeat: {s.lastHeartbeatAt ? new Date(s.lastHeartbeatAt).toLocaleTimeString('it-IT') : '—'}</span></li>)}</ul></section>{workers.length > 0 && <section className="panel praison-monitor"><div className="panel-head"><h2>Worker e task</h2><span className={workers.length > 1 ? 'parallel-badge' : 'muted small'}>{workers.length > 1 ? 'In parallelo' : 'Tracciato'}</span></div><p className="muted small">Rilevati dagli eventi del runtime.</p><ul>{workers.map((w) => <li key={w.id}><strong>{w.id}</strong><span>{w.task ? `Task ${w.task}` : 'Task non indicato'} · {w.events.length} eventi</span></li>)}</ul></section>}</aside></div></>}</div>;
}
